package employee;
// Generated Nov 21, 2015 10:50:07 AM by Hibernate Tools 4.3.1



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {

     private int id;
     private String fristName;
     private String lastName;
     private Integer salary;

    public Employee() {
    }

	
    public Employee(int id) {
        this.id = id;
    }
    public Employee(int id, String fristName, String lastName, Integer salary) {
       this.id = id;
       this.fristName = fristName;
       this.lastName = lastName;
       this.salary = salary;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFristName() {
        return this.fristName;
    }
    
    public void setFristName(String fristName) {
        this.fristName = fristName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Integer getSalary() {
        return this.salary;
    }
    
    public void setSalary(Integer salary) {
        this.salary = salary;
    }




}


